/** モック用の組織レコード群。 */
export const INITIAL_ORGANIZATIONS = [
  {
    code: 'ABCD1234',
    companyName: 'Demo Industries',
    adminName: 'いろはにほへと',
    adminPassword: 'adminpass',
  },
]

/** モック用の作業者アカウント。 */
export const INITIAL_WORKERS = [
  {
    id: 'W001',
    name: '田中太郎',
    team: 'North Survey',
    organizationCode: 'ABCD1234',
    password: 'worker123',
  },
  { id: 'W002', name: '佐藤次郎', team: 'North Survey', organizationCode: 'ABCD1234', password: 'worker123' },
  { id: 'W003', name: '鈴木花子', team: 'North Survey', organizationCode: 'ABCD1234', password: 'worker123' },
  { id: 'W004', name: '李 俊', team: 'West Install', organizationCode: 'ABCD1234', password: 'worker123' },
  { id: 'W005', name: '高橋健太', team: 'West Install', organizationCode: 'ABCD1234', password: 'worker123' },
  { id: 'W006', name: '山本優', team: 'Central Maintenance', organizationCode: 'ABCD1234', password: 'worker123' },
  { id: 'W007', name: '小林正', team: 'Central Maintenance', organizationCode: 'ABCD1234', password: 'worker123' },
  { id: 'W008', name: '近藤亮', team: 'Central Maintenance', organizationCode: 'ABCD1234', password: 'worker123' },
  { id: 'W009', name: '伊藤誠', team: 'South Response', organizationCode: 'ABCD1234', password: 'worker123' },
  { id: 'W010', name: '中村悠', team: 'South Response', organizationCode: 'ABCD1234', password: 'worker123' },
  { id: 'W011', name: '大野健', team: 'South Response', organizationCode: 'ABCD1234', password: 'worker123' },
  { id: 'W012', name: '松本翔', team: 'Support East', organizationCode: 'ABCD1234', password: 'worker123' },
  { id: 'W013', name: '石川優里', team: 'Support East', organizationCode: 'ABCD1234', password: 'worker123' },
]

/** UIデモ用の作業指示レコード。 */
export const seedWorkOrders = [
  {
    id: 'FW-2401',
    db_id: 1,
    projectName: '〇〇建設 第3棟',
    address: '東京都杉並区高円寺1-2-3',
    mapUrl: 'https://maps.example.com/?q=Tokyo+Koenji+1-2-3',
    team: 'North Survey',
    supervisor: 'Ayaka Sato',
    location: 'Sapporo Block 4',
    status: 'In Progress',
    startDate: '2025-05-28T08:30:00+09:00',
    dueDate: '2025-05-28T16:00:00+09:00',
    priority: 'High',
    crewCount: 6,
    progress: 55,
    safetyCheck: 'Cleared',
    notes: 'Awaiting soil test results for quadrant C.',
    taskDescription: '地盤調査ポイントCの再確認と測量補正作業。',
    members: ['W001', 'W002', 'W003'],
    parkingInfo: '裏手コインP／徒歩3分',
    cautionNote: '重量物あり／歩行者通行に注意',
    uploadUrl: 'https://example.com/upload/FW-2401',
    updatedAt: '2025-06-02T08:30:00+09:00',
    resourceUrl: 'https://example.com/docs/FW-2401-plan.pdf',
    upcomingNotes: '2F北側で仮囲い撤去予定。',
  },
  {
    id: 'FW-2402',
    db_id: 2,
    projectName: '物流倉庫 荷捌き場',
    address: '北海道函館市豊川町2-4-1',
    mapUrl: 'https://maps.example.com/?q=Hakodate+Toyokawa',
    team: 'West Install',
    supervisor: 'Daichi Morita',
    location: 'Hakodate Logistics Hub',
    status: 'Ready for Dispatch',
    startDate: '2025-06-04T09:00:00+09:00',
    dueDate: '2025-06-04T17:00:00+09:00',
    priority: 'Medium',
    crewCount: 4,
    progress: 10,
    safetyCheck: 'Pending',
    notes: 'Equipment staging complete; waiting on transport window.',
    taskDescription: '資材到着後の荷下ろしと仮置き場への搬入動線確認。',
    members: ['W004', 'W005'],
    parkingInfo: '北側駐車場／徒歩1分',
    cautionNote: 'フォークリフト優先を徹底',
    uploadUrl: 'https://example.com/upload/FW-2402',
    updatedAt: '2025-06-01T17:05:00+09:00',
    resourceUrl: 'https://example.com/docs/FW-2402-materials.pdf',
    upcomingNotes: '新しい荷揚げ導線を確認してください。',
  },
  {
    id: 'FW-2403',
    db_id: 3,
    team: 'Central Maintenance',
    supervisor: 'Hiroko Watanabe',
    location: 'Asahikawa Substation',
    status: 'Completed',
    startDate: '2025-05-12',
    dueDate: '2025-05-20',
    priority: 'Medium',
    crewCount: 5,
    progress: 100,
    safetyCheck: 'Cleared',
    notes: 'Final report filed; follow-up inspection scheduled for July.',
    taskDescription: '点検結果の最終報告と来月のフォロー点検準備。',
    members: ['W006', 'W007', 'W008'],
    updatedAt: '2025-05-20T15:42:00+09:00',
    resourceUrl: 'https://example.com/docs/FW-2403-report.pdf',
  },
  {
    id: 'FW-2404',
    db_id: 4,
    team: 'South Response',
    supervisor: 'Ken Tanaka',
    location: 'Muroran Coastal Route',
    status: 'Delayed',
    startDate: '2025-05-25',
    dueDate: '2025-06-03',
    priority: 'High',
    crewCount: 8,
    progress: 40,
    safetyCheck: 'Restrictions',
    notes: 'High winds expected; backup crew requested for 6/4.',
    taskDescription: '高所作業の安全監視と、強風時の待機手順確認。',
    members: ['W009', 'W010', 'W011'],
    updatedAt: '2025-06-02T12:15:00+09:00',
    resourceUrl: 'https://example.com/docs/FW-2404-safety.pdf',
  },
  {
    id: 'FW-2405',
    db_id: 5,
    team: 'Support East',
    supervisor: 'Mina Ishikawa',
    location: 'Kushiro Waterworks',
    status: 'Not Started',
    startDate: '2025-06-10',
    dueDate: '2025-06-17',
    priority: 'Low',
    crewCount: 3,
    progress: 0,
    safetyCheck: 'Pending',
    notes: 'Permits finalized; kickoff briefing on 6/7.',
    taskDescription: '着工前ブリーフィングと近隣への周知資料配布。',
    members: ['W012', 'W013'],
    updatedAt: '2025-05-30T09:50:00+09:00',
    resourceUrl: 'https://example.com/docs/FW-2405-briefing.pdf',
  },
]

/** モック用の打刻履歴。 */
const now = new Date()
const today8am = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 8, 0, 0)
const today830 = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 8, 30, 0)
const today12 = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 12, 0, 0)
const today13 = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 13, 0, 0)
const today17 = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 17, 0, 0)

export const seedTimeEntries = [
  {
    id: 'TE001',
    userId: 'W001',
    type: 'clock_in',
    timestamp: today8am.toISOString(),
    latitude: 35.705,
    longitude: 139.6485,
    workOrderId: 'FW-2401',
    note: '',
  },
  {
    id: 'TE002',
    userId: 'W002',
    type: 'clock_in',
    timestamp: today830.toISOString(),
    latitude: 35.7052,
    longitude: 139.649,
    workOrderId: 'FW-2401',
    note: '',
  },
  {
    id: 'TE003',
    userId: 'W001',
    type: 'break_start',
    timestamp: today12.toISOString(),
    latitude: 35.705,
    longitude: 139.6485,
    workOrderId: 'FW-2401',
    note: '昼休憩',
  },
  {
    id: 'TE004',
    userId: 'W001',
    type: 'break_end',
    timestamp: today13.toISOString(),
    latitude: 35.705,
    longitude: 139.6485,
    workOrderId: 'FW-2401',
    note: '',
  },
  {
    id: 'TE005',
    userId: 'W003',
    type: 'clock_in',
    timestamp: today830.toISOString(),
    latitude: 35.7055,
    longitude: 139.6488,
    workOrderId: 'FW-2401',
    note: '',
  },
  {
    id: 'TE006',
    userId: 'W004',
    type: 'clock_in',
    timestamp: today8am.toISOString(),
    latitude: 41.7687,
    longitude: 140.7288,
    workOrderId: 'FW-2402',
    note: '',
  },
  {
    id: 'TE007',
    userId: 'W004',
    type: 'break_start',
    timestamp: today12.toISOString(),
    latitude: 41.7687,
    longitude: 140.7288,
    workOrderId: 'FW-2402',
    note: '',
  },
  {
    id: 'TE008',
    userId: 'W004',
    type: 'break_end',
    timestamp: today13.toISOString(),
    latitude: 41.7687,
    longitude: 140.7288,
    workOrderId: 'FW-2402',
    note: '',
  },
  {
    id: 'TE009',
    userId: 'W006',
    type: 'clock_in',
    timestamp: today8am.toISOString(),
    latitude: 43.7707,
    longitude: 142.365,
    workOrderId: 'FW-2403',
    note: '',
  },
  {
    id: 'TE010',
    userId: 'W006',
    type: 'clock_out',
    timestamp: today17.toISOString(),
    latitude: 43.7707,
    longitude: 142.365,
    workOrderId: 'FW-2403',
    note: '',
  },
  {
    id: 'TE011',
    userId: 'W009',
    type: 'clock_in',
    timestamp: today830.toISOString(),
    latitude: 42.315,
    longitude: 140.973,
    workOrderId: 'FW-2404',
    note: '',
  },
]


